<?xml version="1.0" encoding="utf-8"?><Database Name="SAT_CRP_App" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=THSATITSV052;Initial Catalog=SAT_CRP_App;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SAT_CRP_AppConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmpId" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmpName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>